### PR TITLE
Completing WebHDFS REST API

### PR DESCRIPTION
**Pull request by xaviered**
Small details are missing from WebHDFS REST API at http://hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-hdfs/WebHDFS.html#Concat_Files

This PR completes the missing parts from the two major sections of the API
- File and Directory Operations
- Other File System Operations

@Thanavath I've added the following to the library:
- complete options for the create/createWithData methods
- add the following missing methods from the specs:
-- truncate
-- getTrashRoot
-- modifyAclEntries
-- removeAclEntries
-- removeDefaultAcl
-- removeAcl
-- setAcl
-- getAclStatus
-- checkAccess

### CODE REVIEW

**Comment by xaviered** [comment]
I originally wanted to just add the missing options to the create/createWithData methods because I want to be able to overwrite an existing file. However, I'd figure that I would need the rest and decided to add the rest of the methods.

**Comment by Thanavath** [comment]
Hey @xaviered, we've stopped maintaining this project.
Would you be interested in owning it?  Let me know and I'll transfer the ownership to you.

**Comment by xaviered** [comment]
@Thanavath that would be awesome. Thanks!

**Comment by Thanavath** [comment]
> xaviered/php-WebHDFS already exists and You can only transfer a repository from an organization to yourself at this time

Can you try deleting your fork, and I'll give it another shot.

**Comment by xaviered** [comment]
Alright, It's gone

**Comment by Thanavath** [comment]
Looks like I had to transfer it to myself first, then transfer it to you.  You should be good now.

**Comment by xaviered** [comment]
I received the first request with a link, but that seems to be expired now.
I haven't received another one yet... perhaps may take some time.

**Comment by xaviered** [comment]
I got access to it now. thanks

**Pull request merged**
